services:
#Banco
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    networks:
      - compose-bridge
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepassword
      POSTGRES_DB: gameplatform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gameuser -d gameplatform"]
      interval: 5s
      timeout: 5s
      retries: 5
#API
  api:
    build:
      context: ..
      dockerfile: UserRegistrationAndGameLibrary.Api/Dockerfile
    container_name: api
    networks:
      - compose-bridge
    ports:
      - 8080:8080
networks:
  compose-bridge:
    driver: bridge 

volumes:
  postgres_data: